// AISPM AI use-case registry + types.
//
// Ported verbatim from the AI-SPM dashboard (lib/aimaps-types.ts +
// lib/aimaps-data.ts). The single source of truth for the AI use-case
// inventory; downstream derivations (compliance-metrics, board-risks,
// iso42001-journey) depend on the exact field values here.
//
// Types are namespaced to this module to avoid collisions with atlas's
// entity types. Discovery data (AGENT_CONVERSATIONS / DISCOVERY_STATS)
// lives in @/lib/aispm/discovery.ts and is intentionally NOT duplicated here.

export interface AIModel {
  id: string
  name: string
  provider: string
  type: 'llm' | 'classifier' | 'vision' | 'embedding'
}

export interface Mitigation {
  id: string
  name: string
  description: string
  status: 'applied' | 'pending' | 'not-applied'
  ownerId?: string
  dueDate?: string
}

export type ComplianceLevel = 'covered' | 'partial' | 'gap'

export interface ComplianceStatus {
  euAiAct: ComplianceLevel
  nistAiRmf: ComplianceLevel
  owaspLlm: ComplianceLevel
  iso42001: ComplianceLevel
}

export interface Risk {
  id: string
  name: string
  category: 'hallucination' | 'data-leakage' | 'prompt-injection' | 'bias' | 'ip-exposure' | 'compliance' | 'shadow-ai'
  severity: 'critical' | 'high' | 'medium' | 'low'
  owaspRef?: string
  nistRef?: string
  euAiActRef?: string
  mitigations: Mitigation[]
}

export type UseCaseStatus = 'discovered' | 'assessed' | 'owned' | 'mitigated' | 'compliant'
export type DiscoveryMethod = 'agent-campaign' | 'self-register' | 'auto-detect' | 'shadow-ai'

export interface UseCase {
  id: string
  name: string
  description: string
  department: string
  models: AIModel[]
  ownerId: string | null
  dataClassification: 'public' | 'internal' | 'confidential' | 'restricted'
  risks: Risk[]
  mitigations: Mitigation[]
  complianceStatus: ComplianceStatus
  discoveryMethod: DiscoveryMethod
  status: UseCaseStatus
  createdAt: string
  lastReviewedAt: string
}

export const AI_MODELS: AIModel[] = [
  { id: 'gpt4o', name: 'GPT-4o', provider: 'OpenAI', type: 'llm' },
  { id: 'claude35', name: 'Claude 3.5 Sonnet', provider: 'Anthropic', type: 'llm' },
  { id: 'gemini', name: 'Gemini Pro', provider: 'Google', type: 'llm' },
  { id: 'copilot', name: 'GitHub Copilot', provider: 'Microsoft', type: 'llm' },
  { id: 'llama3', name: 'Llama 3', provider: 'Meta', type: 'llm' },
  { id: 'mistral', name: 'Mistral Large', provider: 'Mistral AI', type: 'llm' },
]

export const USE_CASES: UseCase[] = [
  // === LEGAL (5) ===
  {
    id: 'contract-review',
    name: 'Contract Review AI',
    description: 'Uses GPT-4o to review and summarise legal contracts, flagging unusual clauses and risks for legal counsel review.',
    department: 'Legal',
    models: [AI_MODELS[0]],
    ownerId: 'sarah-chen',
    dataClassification: 'confidential',
    risks: [
      {
        id: 'r-hallucination-legal',
        name: 'Hallucination in legal analysis',
        category: 'hallucination',
        severity: 'critical',
        owaspRef: 'LLM09',
        nistRef: 'GOVERN 1.1',
        euAiActRef: 'Art. 9',
        mitigations: [
          { id: 'm1', name: 'Human review gate', description: 'All AI output reviewed by qualified legal counsel before use', status: 'applied' },
          { id: 'm2', name: 'Output confidence scoring', description: 'Flag low-confidence outputs for additional review', status: 'pending' },
        ],
      },
      {
        id: 'r-data-leak-legal',
        name: 'Confidential data sent to external LLM',
        category: 'data-leakage',
        severity: 'high',
        owaspRef: 'LLM06',
        nistRef: 'MANAGE 2.2',
        euAiActRef: 'Art. 10',
        mitigations: [
          { id: 'm3', name: 'Data minimisation policy', description: 'Strip PII and client names before sending to LLM', status: 'pending' },
        ],
      },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'partial', nistAiRmf: 'partial', owaspLlm: 'covered', iso42001: 'gap' },
    discoveryMethod: 'agent-campaign',
    status: 'assessed',
    createdAt: '2026-03-10T09:00:00Z',
    lastReviewedAt: '2026-03-15T14:30:00Z',
  },
  {
    id: 'legal-brief-summariser',
    name: 'Legal Brief Summariser',
    description: 'Summarises lengthy legal briefs and case documents using Claude 3.5 Sonnet for faster case preparation.',
    department: 'Legal',
    models: [AI_MODELS[1]],
    ownerId: 'sarah-chen',
    dataClassification: 'confidential',
    risks: [
      { id: 'r-halluc-brief', name: 'Missed key legal arguments', category: 'hallucination', severity: 'high', owaspRef: 'LLM09', nistRef: 'GOVERN 1.2', euAiActRef: 'Art. 9', mitigations: [{ id: 'm4', name: 'Senior review required', description: 'Senior counsel must review all AI summaries', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'partial', owaspLlm: 'covered', iso42001: 'partial' },
    discoveryMethod: 'agent-campaign',
    status: 'owned',
    createdAt: '2026-03-10T09:00:00Z',
    lastReviewedAt: '2026-03-15T14:30:00Z',
  },
  {
    id: 'clause-extractor',
    name: 'Clause Extractor',
    description: 'Automatically identifies and extracts specific contract clauses (liability, IP, termination) from uploaded documents.',
    department: 'Legal',
    models: [AI_MODELS[0]],
    ownerId: 'sarah-chen',
    dataClassification: 'confidential',
    risks: [
      { id: 'r-clause-miss', name: 'Critical clause missed', category: 'hallucination', severity: 'high', owaspRef: 'LLM09', mitigations: [{ id: 'm5', name: 'Dual-model verification', description: 'Run clause extraction through two models and compare', status: 'pending' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'partial', nistAiRmf: 'covered', owaspLlm: 'partial', iso42001: 'gap' },
    discoveryMethod: 'agent-campaign',
    status: 'assessed',
    createdAt: '2026-03-11T09:00:00Z',
    lastReviewedAt: '2026-03-15T14:30:00Z',
  },
  {
    id: 'compliance-checker',
    name: 'Compliance Checker',
    description: 'Checks contracts and policies against current regulatory requirements using GPT-4o with a legal knowledge base.',
    department: 'Legal',
    models: [AI_MODELS[0]],
    ownerId: 'sarah-chen',
    dataClassification: 'internal',
    risks: [
      { id: 'r-outdated-regs', name: 'Outdated regulatory knowledge', category: 'compliance', severity: 'high', euAiActRef: 'Art. 13', mitigations: [{ id: 'm6', name: 'Monthly knowledge base update', description: 'Update regulatory reference data monthly', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'partial', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'compliant',
    createdAt: '2026-03-08T09:00:00Z',
    lastReviewedAt: '2026-03-16T10:00:00Z',
  },
  {
    id: 'nda-drafting',
    name: 'NDA Drafting Assistant',
    description: 'Generates first-draft NDAs based on deal parameters, reviewed by legal before sending to counterparties.',
    department: 'Legal',
    models: [AI_MODELS[1]],
    ownerId: 'sarah-chen',
    dataClassification: 'confidential',
    risks: [
      { id: 'r-nda-ip', name: 'IP terms incorrectly drafted', category: 'ip-exposure', severity: 'critical', owaspRef: 'LLM06', euAiActRef: 'Art. 9', mitigations: [{ id: 'm7', name: 'Mandatory legal review', description: 'No NDA sent without partner sign-off', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'partial', nistAiRmf: 'partial', owaspLlm: 'covered', iso42001: 'gap' },
    discoveryMethod: 'agent-campaign',
    status: 'owned',
    createdAt: '2026-03-09T09:00:00Z',
    lastReviewedAt: '2026-03-14T10:00:00Z',
  },

  // === IT (5) ===
  {
    id: 'code-assistant',
    name: 'Code Assistant',
    description: 'GitHub Copilot integrated into VS Code for all engineering staff, with access to internal proprietary codebases.',
    department: 'IT',
    models: [AI_MODELS[3]],
    ownerId: 'james-okafor',
    dataClassification: 'restricted',
    risks: [
      { id: 'r-ip-code', name: 'Proprietary code exposed to model training', category: 'ip-exposure', severity: 'critical', owaspRef: 'LLM06', nistRef: 'MANAGE 2.4', mitigations: [{ id: 'm8', name: 'Enterprise licence with no-train clause', description: 'Ensure Copilot Business contract excludes training', status: 'applied' }] },
      { id: 'r-secrets', name: 'API keys in context window', category: 'data-leakage', severity: 'high', owaspRef: 'LLM02', mitigations: [{ id: 'm9', name: 'Pre-commit secrets scanner', description: 'Block commits with detected secrets', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'partial', iso42001: 'partial' },
    discoveryMethod: 'agent-campaign',
    status: 'mitigated',
    createdAt: '2026-03-05T09:00:00Z',
    lastReviewedAt: '2026-03-17T10:00:00Z',
  },
  {
    id: 'infrastructure-monitoring',
    name: 'Infrastructure Monitoring AI',
    description: 'LLM-based anomaly detection and alert summarisation for cloud infrastructure events.',
    department: 'IT',
    models: [AI_MODELS[2]],
    ownerId: 'james-okafor',
    dataClassification: 'internal',
    risks: [
      { id: 'r-infra-false', name: 'False positive alerts causing downtime', category: 'hallucination', severity: 'medium', mitigations: [{ id: 'm10', name: 'Alert confidence threshold', description: 'Only escalate alerts above 85% confidence', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'covered', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'compliant',
    createdAt: '2026-03-01T09:00:00Z',
    lastReviewedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'incident-summariser',
    name: 'Incident Summariser',
    description: 'Automatically summarises production incidents from logs and Slack threads for post-mortems.',
    department: 'IT',
    models: [AI_MODELS[1]],
    ownerId: 'james-okafor',
    dataClassification: 'internal',
    risks: [
      { id: 'r-inc-miss', name: 'Root cause misattributed', category: 'hallucination', severity: 'medium', owaspRef: 'LLM09', mitigations: [{ id: 'm11', name: 'Engineer validation step', description: 'On-call engineer validates AI summary before sharing', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'partial', owaspLlm: 'covered', iso42001: 'partial' },
    discoveryMethod: 'agent-campaign',
    status: 'owned',
    createdAt: '2026-03-12T09:00:00Z',
    lastReviewedAt: '2026-03-16T10:00:00Z',
  },
  {
    id: 'security-log-analyser',
    name: 'Security Log Analyser',
    description: 'Analyses SIEM logs using an LLM to identify suspicious patterns and generate human-readable threat summaries.',
    department: 'IT',
    models: [AI_MODELS[0]],
    ownerId: 'james-okafor',
    dataClassification: 'restricted',
    risks: [
      { id: 'r-prompt-inject-sec', name: 'Prompt injection via malicious log entries', category: 'prompt-injection', severity: 'critical', owaspRef: 'LLM01', nistRef: 'GOVERN 6.2', euAiActRef: 'Art. 15', mitigations: [{ id: 'm12', name: 'Log sanitisation pipeline', description: 'Sanitise log content before passing to LLM', status: 'pending' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'gap', nistAiRmf: 'partial', owaspLlm: 'gap', iso42001: 'gap' },
    discoveryMethod: 'agent-campaign',
    status: 'assessed',
    createdAt: '2026-03-13T09:00:00Z',
    lastReviewedAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'deployment-describer',
    name: 'Deployment Describer',
    description: 'Generates deployment notes and change summaries from git diffs for release communications.',
    department: 'IT',
    models: [AI_MODELS[3]],
    ownerId: 'james-okafor',
    dataClassification: 'internal',
    risks: [
      { id: 'r-deploy-inaccurate', name: 'Inaccurate change description', category: 'hallucination', severity: 'low', mitigations: [{ id: 'm13', name: 'Dev sign-off', description: 'Lead dev approves release notes before publish', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'covered', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'compliant',
    createdAt: '2026-03-10T09:00:00Z',
    lastReviewedAt: '2026-03-17T10:00:00Z',
  },

  // === CLAIMS (5) ===
  {
    id: 'fraud-detection',
    name: 'Fraud Detection Model',
    description: 'ML classifier that scores insurance claims for fraud likelihood using historical patterns and anomaly detection.',
    department: 'Claims',
    models: [{ id: 'fraud-ml', name: 'Custom Fraud Classifier', provider: 'Internal', type: 'classifier' }],
    ownerId: 'emma-fischer',
    dataClassification: 'restricted',
    risks: [
      { id: 'r-bias-fraud', name: 'Demographic bias in fraud scoring', category: 'bias', severity: 'critical', owaspRef: 'LLM09', nistRef: 'MAP 5.1', euAiActRef: 'Art. 10', mitigations: [{ id: 'm14', name: 'Quarterly bias audit', description: 'Third-party bias audit every quarter', status: 'applied' }, { id: 'm15', name: 'Fairness constraints in model', description: 'Demographic parity enforced in training', status: 'pending' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'partial', nistAiRmf: 'partial', owaspLlm: 'partial', iso42001: 'partial' },
    discoveryMethod: 'agent-campaign',
    status: 'assessed',
    createdAt: '2026-02-01T09:00:00Z',
    lastReviewedAt: '2026-03-10T10:00:00Z',
  },
  {
    id: 'claims-triage',
    name: 'Claims Triage AI',
    description: 'Routes incoming claims to the correct team and priority queue based on claim type, value, and complexity.',
    department: 'Claims',
    models: [AI_MODELS[2]],
    ownerId: 'emma-fischer',
    dataClassification: 'confidential',
    risks: [
      { id: 'r-triage-wrong', name: 'High-value claim misrouted', category: 'hallucination', severity: 'high', euAiActRef: 'Art. 9', mitigations: [{ id: 'm16', name: 'High-value claim override', description: 'Claims over £50k require human routing confirmation', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'partial', nistAiRmf: 'covered', owaspLlm: 'covered', iso42001: 'partial' },
    discoveryMethod: 'agent-campaign',
    status: 'owned',
    createdAt: '2026-02-15T09:00:00Z',
    lastReviewedAt: '2026-03-12T10:00:00Z',
  },
  {
    id: 'damage-assessment',
    name: 'Damage Assessment AI',
    description: 'Analyses photos of vehicle or property damage to estimate repair costs using computer vision.',
    department: 'Claims',
    models: [{ id: 'vision-model', name: 'GPT-4o Vision', provider: 'OpenAI', type: 'vision' }],
    ownerId: 'emma-fischer',
    dataClassification: 'confidential',
    risks: [
      { id: 'r-damage-under', name: 'Underestimated damage leading to disputes', category: 'hallucination', severity: 'high', owaspRef: 'LLM09', mitigations: [{ id: 'm17', name: 'Assessor validation for large claims', description: 'Human assessor reviews AI estimates over £5k', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'partial', owaspLlm: 'covered', iso42001: 'partial' },
    discoveryMethod: 'agent-campaign',
    status: 'mitigated',
    createdAt: '2026-02-20T09:00:00Z',
    lastReviewedAt: '2026-03-14T10:00:00Z',
  },
  {
    id: 'claims-letter-gen',
    name: 'Claims Letter Generator',
    description: 'Generates outcome letters for claimants based on claim decisions, personalised with relevant policy details.',
    department: 'Claims',
    models: [AI_MODELS[1]],
    ownerId: 'emma-fischer',
    dataClassification: 'confidential',
    risks: [
      { id: 'r-letter-wrong', name: 'Incorrect policy terms communicated', category: 'compliance', severity: 'high', euAiActRef: 'Art. 9', mitigations: [{ id: 'm18', name: 'Template guardrails', description: 'Letters restricted to approved templates', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'partial', nistAiRmf: 'covered', owaspLlm: 'partial', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'owned',
    createdAt: '2026-03-01T09:00:00Z',
    lastReviewedAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'subrogation-analyser',
    name: 'Subrogation Analyser',
    description: 'Identifies subrogation opportunities in settled claims by analysing case details against third-party liability indicators.',
    department: 'Claims',
    models: [AI_MODELS[0]],
    ownerId: 'emma-fischer',
    dataClassification: 'confidential',
    risks: [
      { id: 'r-subrog-miss', name: 'Missed subrogation opportunity', category: 'hallucination', severity: 'medium', mitigations: [{ id: 'm19', name: 'Weekly manual audit sample', description: 'Random 10% of cases reviewed by senior adjuster', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'covered', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'compliant',
    createdAt: '2026-03-05T09:00:00Z',
    lastReviewedAt: '2026-03-17T10:00:00Z',
  },

  // === CUSTOMER SERVICE (5) ===
  {
    id: 'customer-chatbot',
    name: 'Customer Chat Bot',
    description: 'Customer-facing AI chatbot handling policy queries, claims status updates, and general insurance questions.',
    department: 'Customer Service',
    models: [AI_MODELS[0]],
    ownerId: 'alex-kumar',
    dataClassification: 'internal',
    risks: [
      { id: 'r-chat-wrong', name: 'Incorrect policy advice given to customers', category: 'hallucination', severity: 'critical', owaspRef: 'LLM09', euAiActRef: 'Art. 9', mitigations: [{ id: 'm20', name: 'Knowledge base grounding', description: 'Responses grounded only in approved policy documents', status: 'applied' }, { id: 'm21', name: 'Regulatory disclaimer', description: 'All AI responses include FCA disclaimer', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'partial', nistAiRmf: 'covered', owaspLlm: 'covered', iso42001: 'partial' },
    discoveryMethod: 'agent-campaign',
    status: 'mitigated',
    createdAt: '2026-01-15T09:00:00Z',
    lastReviewedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'complaint-classifier',
    name: 'Complaint Classifier',
    description: 'Categorises customer complaints by type and urgency for FCA reporting and team routing.',
    department: 'Customer Service',
    models: [AI_MODELS[1]],
    ownerId: 'alex-kumar',
    dataClassification: 'confidential',
    risks: [
      { id: 'r-complaint-mis', name: 'FCA-reportable complaint misclassified', category: 'compliance', severity: 'critical', euAiActRef: 'Art. 9', mitigations: [{ id: 'm22', name: 'Compliance team override queue', description: 'All critical complaints reviewed by compliance', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'covered', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'compliant',
    createdAt: '2026-01-20T09:00:00Z',
    lastReviewedAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'sentiment-tracker',
    name: 'Sentiment Tracker',
    description: 'Monitors customer interaction sentiment in real-time to flag at-risk relationships to account managers.',
    department: 'Customer Service',
    models: [{ id: 'sentiment-model', name: 'Custom Sentiment Model', provider: 'Internal', type: 'classifier' }],
    ownerId: 'alex-kumar',
    dataClassification: 'internal',
    risks: [
      { id: 'r-sentiment-bias', name: 'Biased sentiment scoring by dialect', category: 'bias', severity: 'medium', owaspRef: 'LLM09', mitigations: [{ id: 'm23', name: 'Dialect-balanced training data', description: 'Model retrained with balanced regional dialect data', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'covered', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'compliant',
    createdAt: '2026-02-01T09:00:00Z',
    lastReviewedAt: '2026-03-16T10:00:00Z',
  },
  {
    id: 'response-suggester',
    name: 'Response Suggester',
    description: 'Suggests reply templates to agents based on customer query context and historical successful responses.',
    department: 'Customer Service',
    models: [AI_MODELS[1]],
    ownerId: 'alex-kumar',
    dataClassification: 'internal',
    risks: [
      { id: 'r-resp-off', name: 'Inappropriate tone in customer response', category: 'hallucination', severity: 'low', mitigations: [{ id: 'm24', name: 'Agent always edits suggestion', description: 'UI enforces editing before send', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'covered', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'compliant',
    createdAt: '2026-02-10T09:00:00Z',
    lastReviewedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'faq-generator',
    name: 'FAQ Generator',
    description: 'Automatically generates FAQ content from product documentation and common customer queries.',
    department: 'Customer Service',
    models: [AI_MODELS[0]],
    ownerId: 'alex-kumar',
    dataClassification: 'public',
    risks: [
      { id: 'r-faq-inaccurate', name: 'Inaccurate FAQ content published', category: 'compliance', severity: 'medium', mitigations: [{ id: 'm25', name: 'Content editor approval', description: 'All FAQ content reviewed before publishing', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'covered', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'compliant',
    createdAt: '2026-02-15T09:00:00Z',
    lastReviewedAt: '2026-03-17T10:00:00Z',
  },

  // === HR (5) ===
  {
    id: 'cv-screening',
    name: 'CV Screening',
    description: 'AI classifier that ranks candidate CVs for shortlisting. Processes photos and personal data from uploaded documents.',
    department: 'HR',
    models: [{ id: 'cv-classifier', name: 'CV Classifier', provider: 'HireVue', type: 'classifier' }],
    ownerId: 'priya-sharma',
    dataClassification: 'restricted',
    risks: [
      { id: 'r-cv-bias', name: 'Age/gender/nationality bias in ranking', category: 'bias', severity: 'critical', owaspRef: 'LLM09', nistRef: 'MAP 5.1', euAiActRef: 'Art. 10', mitigations: [{ id: 'm26', name: 'Protected characteristics filter', description: 'Configure system to ignore protected characteristics', status: 'not-applied' }, { id: 'm27', name: 'Bias audit before use in hiring', description: 'Independent bias assessment required before deployment', status: 'pending' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'gap', nistAiRmf: 'gap', owaspLlm: 'partial', iso42001: 'gap' },
    discoveryMethod: 'agent-campaign',
    status: 'discovered',
    createdAt: '2026-03-15T09:00:00Z',
    lastReviewedAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'job-description-gen',
    name: 'Job Description Generator',
    description: 'Creates job descriptions from role requirements using ChatGPT, edited by HR before publishing.',
    department: 'HR',
    models: [AI_MODELS[0]],
    ownerId: 'priya-sharma',
    dataClassification: 'public',
    risks: [
      { id: 'r-jd-bias', name: 'Biased language in job descriptions', category: 'bias', severity: 'medium', owaspRef: 'LLM09', mitigations: [{ id: 'm28', name: 'Inclusive language checker', description: 'Run output through gender decoder tool', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'covered', iso42001: 'partial' },
    discoveryMethod: 'agent-campaign',
    status: 'owned',
    createdAt: '2026-03-01T09:00:00Z',
    lastReviewedAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'interview-scorer',
    name: 'Interview Scorer',
    description: 'Scores recorded video interviews using facial analysis and speech patterns to predict job suitability.',
    department: 'HR',
    models: [{ id: 'interview-ai', name: 'Interview AI', provider: 'HireVue', type: 'vision' }],
    ownerId: 'priya-sharma',
    dataClassification: 'restricted',
    risks: [
      { id: 'r-interview-bias', name: 'Facial analysis discriminates on protected characteristics', category: 'bias', severity: 'critical', owaspRef: 'LLM09', euAiActRef: 'Art. 5', mitigations: [{ id: 'm29', name: 'Disable facial analysis', description: 'Switch to voice-only analysis mode pending review', status: 'pending' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'gap', nistAiRmf: 'gap', owaspLlm: 'partial', iso42001: 'gap' },
    discoveryMethod: 'agent-campaign',
    status: 'discovered',
    createdAt: '2026-03-16T09:00:00Z',
    lastReviewedAt: '2026-03-16T10:00:00Z',
  },
  {
    id: 'onboarding-assistant',
    name: 'Onboarding Assistant',
    description: 'AI chatbot that guides new employees through onboarding tasks, answering HR policy questions.',
    department: 'HR',
    models: [AI_MODELS[1]],
    ownerId: 'priya-sharma',
    dataClassification: 'internal',
    risks: [
      { id: 'r-onboard-wrong', name: 'Incorrect policy guidance to new employees', category: 'compliance', severity: 'medium', mitigations: [{ id: 'm30', name: 'HR policy grounding', description: 'Chatbot restricted to approved HR policy documents', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'covered', iso42001: 'partial' },
    discoveryMethod: 'agent-campaign',
    status: 'owned',
    createdAt: '2026-03-05T09:00:00Z',
    lastReviewedAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'salary-benchmarker',
    name: 'Salary Benchmarker',
    description: 'Analyses market salary data to recommend compensation ranges for open roles.',
    department: 'HR',
    models: [AI_MODELS[0]],
    ownerId: 'priya-sharma',
    dataClassification: 'confidential',
    risks: [
      { id: 'r-salary-stale', name: 'Outdated salary data leads to underpaying', category: 'hallucination', severity: 'medium', mitigations: [{ id: 'm31', name: 'Quarterly data refresh', description: 'Market data refreshed from verified sources quarterly', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'partial', owaspLlm: 'covered', iso42001: 'partial' },
    discoveryMethod: 'agent-campaign',
    status: 'owned',
    createdAt: '2026-03-10T09:00:00Z',
    lastReviewedAt: '2026-03-15T10:00:00Z',
  },

  // === FINANCE (5) ===
  {
    id: 'report-generator',
    name: 'Report Generator',
    description: 'Generates financial reports and board summaries from raw data using GPT-4o with structured templates.',
    department: 'Finance',
    models: [AI_MODELS[0]],
    ownerId: 'marco-rossi',
    dataClassification: 'restricted',
    risks: [
      { id: 'r-report-err', name: 'Numerical error in financial report', category: 'hallucination', severity: 'critical', owaspRef: 'LLM09', euAiActRef: 'Art. 13', mitigations: [{ id: 'm32', name: 'CFO sign-off required', description: 'All AI-generated reports reviewed and signed by CFO', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'partial', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'mitigated',
    createdAt: '2026-02-01T09:00:00Z',
    lastReviewedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'budget-forecasting',
    name: 'Budget Forecasting AI',
    description: 'Predicts departmental budget requirements based on historical spend patterns and business forecasts.',
    department: 'Finance',
    models: [AI_MODELS[0]],
    ownerId: 'marco-rossi',
    dataClassification: 'restricted',
    risks: [
      { id: 'r-budget-wrong', name: 'Inaccurate forecast leads to over/underspend', category: 'hallucination', severity: 'high', mitigations: [{ id: 'm33', name: 'Finance team validation', description: 'Finance analysts review all AI forecasts', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'covered', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'compliant',
    createdAt: '2026-02-10T09:00:00Z',
    lastReviewedAt: '2026-03-17T10:00:00Z',
  },
  {
    id: 'invoice-classifier',
    name: 'Invoice Classifier',
    description: 'Automatically categorises and routes supplier invoices for approval based on amount and category.',
    department: 'Finance',
    models: [{ id: 'invoice-ml', name: 'Invoice Classifier ML', provider: 'Internal', type: 'classifier' }],
    ownerId: 'marco-rossi',
    dataClassification: 'confidential',
    risks: [
      { id: 'r-invoice-wrong', name: 'Invoice routed to wrong approver', category: 'compliance', severity: 'medium', mitigations: [{ id: 'm34', name: 'Dual approval for high-value invoices', description: 'Invoices over £10k require two approvers', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'covered', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'compliant',
    createdAt: '2026-01-15T09:00:00Z',
    lastReviewedAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'expense-anomaly',
    name: 'Expense Anomaly Detector',
    description: 'Flags unusual expense claims for review using pattern matching and LLM reasoning.',
    department: 'Finance',
    models: [AI_MODELS[1]],
    ownerId: 'marco-rossi',
    dataClassification: 'confidential',
    risks: [
      { id: 'r-expense-fp', name: 'False positives damaging employee trust', category: 'bias', severity: 'medium', mitigations: [{ id: 'm35', name: 'Employee appeal process', description: 'Clear process for challenging AI decisions', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'partial', owaspLlm: 'covered', iso42001: 'partial' },
    discoveryMethod: 'agent-campaign',
    status: 'owned',
    createdAt: '2026-02-20T09:00:00Z',
    lastReviewedAt: '2026-03-16T10:00:00Z',
  },
  {
    id: 'earnings-summariser',
    name: 'Earnings Summariser',
    description: 'Generates plain-language earnings summaries from financial results for investor communications.',
    department: 'Finance',
    models: [AI_MODELS[1]],
    ownerId: 'marco-rossi',
    dataClassification: 'restricted',
    risks: [
      { id: 'r-earnings-wrong', name: 'Material misstatement in investor communication', category: 'compliance', severity: 'critical', euAiActRef: 'Art. 13', mitigations: [{ id: 'm36', name: 'Legal and CFO review', description: 'Investor comms reviewed by legal and CFO before release', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'partial', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'mitigated',
    createdAt: '2026-03-01T09:00:00Z',
    lastReviewedAt: '2026-03-18T10:00:00Z',
  },

  // === RISK & COMPLIANCE (5) ===
  {
    id: 'risk-scoring',
    name: 'Risk Scoring Model',
    description: 'Quantitative risk scoring model for enterprise risk register using LLM to assess narrative risk descriptions.',
    department: 'Risk & Compliance',
    models: [AI_MODELS[0]],
    ownerId: 'lisa-wang',
    dataClassification: 'confidential',
    risks: [
      { id: 'r-risk-wrong', name: 'Risk underscored leading to insufficient controls', category: 'hallucination', severity: 'high', euAiActRef: 'Art. 9', mitigations: [{ id: 'm37', name: 'CRO validation', description: 'CRO reviews all risk scores above threshold', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'covered', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'compliant',
    createdAt: '2026-01-10T09:00:00Z',
    lastReviewedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'regulatory-change',
    name: 'Regulatory Change Monitor',
    description: 'Monitors regulatory publications and alerts compliance team to relevant changes requiring policy updates.',
    department: 'Risk & Compliance',
    models: [AI_MODELS[1]],
    ownerId: 'lisa-wang',
    dataClassification: 'internal',
    risks: [
      { id: 'r-reg-miss', name: 'Critical regulatory change missed', category: 'compliance', severity: 'high', euAiActRef: 'Art. 9', mitigations: [{ id: 'm38', name: 'Weekly compliance review meeting', description: 'AI output reviewed weekly by compliance team', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'covered', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'compliant',
    createdAt: '2026-01-15T09:00:00Z',
    lastReviewedAt: '2026-03-17T10:00:00Z',
  },
  {
    id: 'policy-gap',
    name: 'Policy Gap Analyser',
    description: 'Identifies gaps in internal policies against regulatory requirements using LLM document comparison.',
    department: 'Risk & Compliance',
    models: [AI_MODELS[0]],
    ownerId: 'lisa-wang',
    dataClassification: 'confidential',
    risks: [
      { id: 'r-policy-gap', name: 'False sense of compliance from missed gap', category: 'compliance', severity: 'high', mitigations: [{ id: 'm39', name: 'Annual external audit', description: 'External auditors verify AI gap analysis annually', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'partial', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'compliant',
    createdAt: '2026-02-01T09:00:00Z',
    lastReviewedAt: '2026-03-16T10:00:00Z',
  },
  {
    id: 'audit-trail',
    name: 'Audit Trail Summariser',
    description: 'Generates readable audit trail summaries from raw transaction logs for regulatory submissions.',
    department: 'Risk & Compliance',
    models: [AI_MODELS[1]],
    ownerId: 'lisa-wang',
    dataClassification: 'restricted',
    risks: [
      { id: 'r-audit-incomplete', name: 'Incomplete audit trail submitted to regulator', category: 'compliance', severity: 'critical', euAiActRef: 'Art. 12', mitigations: [{ id: 'm40', name: 'Raw log appended', description: 'AI summary always accompanied by full raw log', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'covered', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'compliant',
    createdAt: '2026-01-20T09:00:00Z',
    lastReviewedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'sanctions-screener',
    name: 'Sanctions Screener',
    description: 'Screens customers and counterparties against global sanctions lists using name-matching ML model.',
    department: 'Risk & Compliance',
    models: [{ id: 'sanctions-ml', name: 'Sanctions ML', provider: 'LexisNexis', type: 'classifier' }],
    ownerId: 'lisa-wang',
    dataClassification: 'restricted',
    risks: [
      { id: 'r-sanctions-miss', name: 'Sanctioned entity not detected', category: 'compliance', severity: 'critical', euAiActRef: 'Art. 9', mitigations: [{ id: 'm41', name: 'Manual review queue for fuzzy matches', description: 'All matches below 95% confidence reviewed by compliance', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'covered', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'compliant',
    createdAt: '2026-01-01T09:00:00Z',
    lastReviewedAt: '2026-03-18T10:00:00Z',
  },

  // === UNDERWRITING (5) ===
  {
    id: 'policy-risk',
    name: 'Policy Risk Assessor',
    description: 'Assesses risk level of new policy applications using a combination of ML models and LLM reasoning.',
    department: 'Underwriting',
    models: [AI_MODELS[0], { id: 'uw-ml', name: 'Underwriting ML', provider: 'Internal', type: 'classifier' }],
    ownerId: 'tom-bradley',
    dataClassification: 'restricted',
    risks: [
      { id: 'r-uw-bias', name: 'Discriminatory risk scoring by postcode/demographics', category: 'bias', severity: 'critical', owaspRef: 'LLM09', euAiActRef: 'Art. 10', mitigations: [{ id: 'm42', name: 'FCA fairness testing', description: 'Quarterly fairness tests against FCA requirements', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'partial', nistAiRmf: 'partial', owaspLlm: 'partial', iso42001: 'partial' },
    discoveryMethod: 'agent-campaign',
    status: 'assessed',
    createdAt: '2026-01-15T09:00:00Z',
    lastReviewedAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'pricing-explainer',
    name: 'Pricing Model Explainer',
    description: 'Generates plain-language explanations of why a customer received a particular premium quote.',
    department: 'Underwriting',
    models: [AI_MODELS[1]],
    ownerId: 'tom-bradley',
    dataClassification: 'confidential',
    risks: [
      { id: 'r-price-explain', name: 'Inaccurate explanation of pricing factors', category: 'compliance', severity: 'high', euAiActRef: 'Art. 13', mitigations: [{ id: 'm43', name: 'Pricing model audit trail', description: 'Explanations verified against actual model inputs', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'covered', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'compliant',
    createdAt: '2026-02-01T09:00:00Z',
    lastReviewedAt: '2026-03-17T10:00:00Z',
  },
  {
    id: 'risk-appetite',
    name: 'Risk Appetite Checker',
    description: 'Checks proposed policy terms against the company risk appetite framework and flags exceptions.',
    department: 'Underwriting',
    models: [AI_MODELS[0]],
    ownerId: 'tom-bradley',
    dataClassification: 'confidential',
    risks: [
      { id: 'r-appetite-wrong', name: 'Risk appetite exception not caught', category: 'compliance', severity: 'high', mitigations: [{ id: 'm44', name: 'Weekly exception report', description: 'All exceptions reviewed by Chief Underwriter weekly', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'covered', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'compliant',
    createdAt: '2026-02-10T09:00:00Z',
    lastReviewedAt: '2026-03-17T10:00:00Z',
  },
  {
    id: 'portfolio-analyser',
    name: 'Portfolio Analyser',
    description: 'Analyses the underwriting portfolio for concentration risk and emerging trends using LLM on structured data.',
    department: 'Underwriting',
    models: [AI_MODELS[2]],
    ownerId: 'tom-bradley',
    dataClassification: 'restricted',
    risks: [
      { id: 'r-portfolio-conc', name: 'Concentration risk underestimated', category: 'hallucination', severity: 'high', mitigations: [{ id: 'm45', name: 'Monthly actuarial review', description: 'Actuarial team reviews AI portfolio analysis monthly', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'partial', owaspLlm: 'covered', iso42001: 'partial' },
    discoveryMethod: 'agent-campaign',
    status: 'owned',
    createdAt: '2026-02-15T09:00:00Z',
    lastReviewedAt: '2026-03-16T10:00:00Z',
  },
  {
    id: 'renewal-predictor',
    name: 'Renewal Predictor',
    description: 'Predicts policy renewal likelihood to prioritise retention outreach efforts.',
    department: 'Underwriting',
    models: [{ id: 'renewal-ml', name: 'Renewal Predictor ML', provider: 'Internal', type: 'classifier' }],
    ownerId: 'tom-bradley',
    dataClassification: 'confidential',
    risks: [
      { id: 'r-renewal-drift', name: 'Model drift reducing prediction accuracy', category: 'compliance', severity: 'medium', mitigations: [{ id: 'm46', name: 'Monthly model performance monitoring', description: 'Track accuracy metrics and trigger retraining when degraded', status: 'applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'covered', iso42001: 'covered' },
    discoveryMethod: 'agent-campaign',
    status: 'compliant',
    createdAt: '2026-02-01T09:00:00Z',
    lastReviewedAt: '2026-03-17T10:00:00Z',
  },

  // === SHADOW AI (12) ===
  {
    id: 'shadow-chatgpt',
    name: 'Personal ChatGPT Use',
    description: 'Multiple employees using personal ChatGPT accounts for work tasks including processing client data.',
    department: 'Various',
    models: [AI_MODELS[0]],
    ownerId: null,
    dataClassification: 'confidential',
    risks: [
      { id: 'r-shadow-leak', name: 'Client data sent to personal AI account', category: 'data-leakage', severity: 'critical', owaspRef: 'LLM06', euAiActRef: 'Art. 10', mitigations: [{ id: 'ms1', name: 'Block personal AI accounts at network level', description: 'IT to block consumer AI endpoints', status: 'not-applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'gap', nistAiRmf: 'gap', owaspLlm: 'gap', iso42001: 'gap' },
    discoveryMethod: 'shadow-ai',
    status: 'discovered',
    createdAt: '2026-03-18T10:00:00Z',
    lastReviewedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'shadow-notion-ai',
    name: 'Notion AI',
    description: 'Marketing team using Notion AI to draft content and summarise meeting notes containing client information.',
    department: 'Various',
    models: [{ id: 'notion-ai', name: 'Notion AI', provider: 'Notion', type: 'llm' }],
    ownerId: null,
    dataClassification: 'internal',
    risks: [
      { id: 'r-notion-data', name: 'Meeting notes with client names in Notion AI', category: 'data-leakage', severity: 'high', owaspRef: 'LLM06', mitigations: [{ id: 'ms2', name: 'Acceptable use policy', description: 'Update AUP to explicitly cover SaaS AI tools', status: 'pending' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'gap', nistAiRmf: 'gap', owaspLlm: 'gap', iso42001: 'gap' },
    discoveryMethod: 'shadow-ai',
    status: 'discovered',
    createdAt: '2026-03-18T10:00:00Z',
    lastReviewedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'shadow-grammarly',
    name: 'Grammarly with Confidential Data',
    description: 'Staff using Grammarly browser extension while drafting confidential documents and emails.',
    department: 'Various',
    models: [{ id: 'grammarly', name: 'Grammarly AI', provider: 'Grammarly', type: 'llm' }],
    ownerId: null,
    dataClassification: 'confidential',
    risks: [
      { id: 'r-gram-data', name: 'Confidential email content sent to Grammarly servers', category: 'data-leakage', severity: 'high', owaspRef: 'LLM06', mitigations: [{ id: 'ms3', name: 'Block Grammarly extension on managed devices', description: 'Remove browser extension from managed devices', status: 'pending' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'gap', nistAiRmf: 'gap', owaspLlm: 'gap', iso42001: 'gap' },
    discoveryMethod: 'shadow-ai',
    status: 'discovered',
    createdAt: '2026-03-18T10:00:00Z',
    lastReviewedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'shadow-copilot-unlicensed',
    name: 'GitHub Copilot (Unlicensed)',
    description: 'Contractors using personal GitHub Copilot accounts with access to proprietary codebase repositories.',
    department: 'IT',
    models: [AI_MODELS[3]],
    ownerId: null,
    dataClassification: 'restricted',
    risks: [
      { id: 'r-copilot-ip', name: 'Proprietary code exposed via personal Copilot account', category: 'ip-exposure', severity: 'critical', owaspRef: 'LLM06', mitigations: [{ id: 'ms4', name: 'Enforce enterprise-only Copilot via policy', description: 'Block personal GitHub tokens in CI/CD', status: 'not-applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'gap', nistAiRmf: 'gap', owaspLlm: 'gap', iso42001: 'gap' },
    discoveryMethod: 'shadow-ai',
    status: 'discovered',
    createdAt: '2026-03-18T10:00:00Z',
    lastReviewedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'shadow-midjourney',
    name: 'Midjourney for Marketing',
    description: 'Marketing team generating campaign images with Midjourney without IP or copyright review.',
    department: 'Various',
    models: [{ id: 'midjourney', name: 'Midjourney', provider: 'Midjourney', type: 'vision' }],
    ownerId: null,
    dataClassification: 'public',
    risks: [
      { id: 'r-mid-ip', name: 'Copyright infringement in generated images', category: 'ip-exposure', severity: 'high', mitigations: [{ id: 'ms5', name: 'IP review process for AI images', description: 'Legal to review all AI-generated images before use', status: 'not-applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'gap', nistAiRmf: 'gap', owaspLlm: 'partial', iso42001: 'gap' },
    discoveryMethod: 'shadow-ai',
    status: 'discovered',
    createdAt: '2026-03-18T10:00:00Z',
    lastReviewedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'shadow-perplexity',
    name: 'Perplexity for Research',
    description: 'Analysts using Perplexity AI to research competitors and market trends, sharing internal strategy context.',
    department: 'Various',
    models: [{ id: 'perplexity', name: 'Perplexity AI', provider: 'Perplexity', type: 'llm' }],
    ownerId: null,
    dataClassification: 'confidential',
    risks: [
      { id: 'r-perp-strat', name: 'Strategic information in research prompts', category: 'data-leakage', severity: 'high', owaspRef: 'LLM06', mitigations: [{ id: 'ms6', name: 'Prompt hygiene training', description: 'Training on what not to include in AI prompts', status: 'pending' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'gap', nistAiRmf: 'gap', owaspLlm: 'gap', iso42001: 'gap' },
    discoveryMethod: 'shadow-ai',
    status: 'discovered',
    createdAt: '2026-03-18T10:00:00Z',
    lastReviewedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'shadow-claude-personal',
    name: 'Claude.ai Personal Account',
    description: 'Senior employees using personal Claude.ai accounts to process board papers and strategic documents.',
    department: 'Various',
    models: [AI_MODELS[1]],
    ownerId: null,
    dataClassification: 'restricted',
    risks: [
      { id: 'r-board-leak', name: 'Board-level strategic documents processed externally', category: 'data-leakage', severity: 'critical', owaspRef: 'LLM06', euAiActRef: 'Art. 10', mitigations: [{ id: 'ms7', name: 'Provision enterprise Claude instance', description: 'Set up Claude for Enterprise with DPA and data residency', status: 'pending' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'gap', nistAiRmf: 'gap', owaspLlm: 'gap', iso42001: 'gap' },
    discoveryMethod: 'shadow-ai',
    status: 'discovered',
    createdAt: '2026-03-18T10:00:00Z',
    lastReviewedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'shadow-otter',
    name: 'Otter.ai for Client Calls',
    description: 'Sales team recording and transcribing client calls with Otter.ai without client consent or DPA.',
    department: 'Various',
    models: [{ id: 'otter', name: 'Otter.ai', provider: 'Otter.ai', type: 'llm' }],
    ownerId: null,
    dataClassification: 'confidential',
    risks: [
      { id: 'r-otter-gdpr', name: 'GDPR violation — recording without consent', category: 'compliance', severity: 'critical', euAiActRef: 'Art. 10', mitigations: [{ id: 'ms8', name: 'Immediate cessation pending review', description: 'Stop using Otter.ai until GDPR assessment complete', status: 'not-applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'gap', nistAiRmf: 'gap', owaspLlm: 'gap', iso42001: 'gap' },
    discoveryMethod: 'shadow-ai',
    status: 'discovered',
    createdAt: '2026-03-18T10:00:00Z',
    lastReviewedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'shadow-whisper',
    name: 'Whisper Meeting Transcription',
    description: 'IT team using OpenAI Whisper API to transcribe internal meetings containing personnel discussions.',
    department: 'IT',
    models: [{ id: 'whisper', name: 'OpenAI Whisper', provider: 'OpenAI', type: 'llm' }],
    ownerId: null,
    dataClassification: 'confidential',
    risks: [
      { id: 'r-whisper-hr', name: 'HR and personnel data in transcripts', category: 'data-leakage', severity: 'high', owaspRef: 'LLM06', mitigations: [{ id: 'ms9', name: 'Switch to on-premise transcription', description: 'Deploy local Whisper instance for sensitive meetings', status: 'pending' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'gap', nistAiRmf: 'gap', owaspLlm: 'gap', iso42001: 'gap' },
    discoveryMethod: 'shadow-ai',
    status: 'discovered',
    createdAt: '2026-03-18T10:00:00Z',
    lastReviewedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'shadow-jasper',
    name: 'Jasper for Content',
    description: 'Marketing using Jasper to write product descriptions and press releases without brand guidelines review.',
    department: 'Various',
    models: [{ id: 'jasper', name: 'Jasper AI', provider: 'Jasper', type: 'llm' }],
    ownerId: null,
    dataClassification: 'public',
    risks: [
      { id: 'r-jasper-brand', name: 'Off-brand or inaccurate content published', category: 'compliance', severity: 'medium', mitigations: [{ id: 'ms10', name: 'Content approval workflow', description: 'All AI content reviewed by brand team before publish', status: 'not-applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'gap', nistAiRmf: 'gap', owaspLlm: 'partial', iso42001: 'gap' },
    discoveryMethod: 'shadow-ai',
    status: 'discovered',
    createdAt: '2026-03-18T10:00:00Z',
    lastReviewedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'shadow-copyai',
    name: 'Copy.ai for Sales Emails',
    description: 'Sales team using Copy.ai to write prospect emails including customer account details.',
    department: 'Various',
    models: [{ id: 'copyai', name: 'Copy.ai', provider: 'Copy.ai', type: 'llm' }],
    ownerId: null,
    dataClassification: 'confidential',
    risks: [
      { id: 'r-copy-crm', name: 'CRM data in sales email prompts', category: 'data-leakage', severity: 'high', owaspRef: 'LLM06', mitigations: [{ id: 'ms11', name: 'Provide approved sales AI tool', description: 'Provide approved alternative with DPA in place', status: 'pending' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'gap', nistAiRmf: 'gap', owaspLlm: 'gap', iso42001: 'gap' },
    discoveryMethod: 'shadow-ai',
    status: 'discovered',
    createdAt: '2026-03-18T10:00:00Z',
    lastReviewedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'shadow-chatpdf',
    name: 'ChatPDF for Contracts',
    description: 'Finance team uploading confidential client contracts to ChatPDF for quick summarisation.',
    department: 'Finance',
    models: [{ id: 'chatpdf', name: 'ChatPDF', provider: 'ChatPDF', type: 'llm' }],
    ownerId: null,
    dataClassification: 'confidential',
    risks: [
      { id: 'r-chatpdf-leak', name: 'Confidential contract data uploaded to unapproved service', category: 'data-leakage', severity: 'critical', owaspRef: 'LLM06', euAiActRef: 'Art. 10', mitigations: [{ id: 'ms12', name: 'Block ChatPDF at proxy', description: 'Block chatpdf.com at web proxy immediately', status: 'not-applied' }] },
    ],
    mitigations: [],
    complianceStatus: { euAiAct: 'gap', nistAiRmf: 'gap', owaspLlm: 'gap', iso42001: 'gap' },
    discoveryMethod: 'shadow-ai',
    status: 'discovered',
    createdAt: '2026-03-18T10:00:00Z',
    lastReviewedAt: '2026-03-18T10:00:00Z',
  },
]
